services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.prodresolver.acme.email=mohsumzadah@gmail.com"
      - "--certificatesresolvers.prodresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.prodresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.prodresolver.acme.httpchallenge.entrypoint=web"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - peco-network

  db:
    image: mysql:8.0
    container_name: pecodev-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - peco-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: pecodev-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy # Changes this from just "- db"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    networks:
      - peco-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`pecodev.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=prodresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    container_name: pecodev-frontend
    restart: always
    networks:
      - peco-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`pecodev.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=prodresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

volumes:
  mysql_data:

networks:
  peco-network:
    driver: bridge